;;; Automatically generated by ‘recentf’ on Wed Apr 24 11:18:12 2024.

(setq recentf-list
      '(
        "~/Documents/Pessoal/language.org"
        "~/.config/emacs/bookmarks"
        "~/.config/emacs/etc/yasnippet/snippets/org-mode/org-to-latex"
        "~/.config/emacs/init.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
