;;; Automatically generated by ‘recentf’ on Thu May 16 13:43:24 2024.

(setq recentf-list
      '(
        "~/.dotfiles/.config/emacs/init.el"
        "~/.config/emacs/init.el"
        "~/.dotfiles/.config/emacs/var/bookmark-default.el"
        "~/.config/emacs/var/bookmark-default.el"
        "~/Documents/Pessoal/language.org"
        "~/.config/emacs/bookmarks"
        "~/.config/emacs/etc/yasnippet/snippets/org-mode/org-to-latex"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
