;;; Automatically generated by ‘recentf’ on Wed Jan 17 21:51:20 2024.

(setq recentf-list
      '(
        "~/Documents/Pessoal/language.org"
        "~/Library/Mobile Documents/com~apple~CloudDocs/escola/3ano/lusofonia.org"
        "~/Documents/org/latexSetup.org"
        "~/.config/emacs/bookmarks"
        "~/Library/Mobile Documents/com~apple~CloudDocs/escola/3ano/A cura de schopenhauer.org"
        "~/.config/emacs/etc/yasnippet/snippets/org-mode/org-to-latex"
        "~/Library/Mobile Documents/com~apple~CloudDocs/escola/3ano/nietzsche.org"
        "~/.config/emacs/init.el"
        "~/Library/Mobile Documents/com~apple~CloudDocs/escola/3ano/nietzsche.tex"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
